--- # Arithmetic Calculator
 - hosts: 192.168.2.114
   user: ansible
   become: yes
   connection: ssh
   vars_prompt:
           - name: a
             prompt: Enter a value
           - name: b
             prompt: Enter b value
   vars:
           addition: "{{a|int+b|int}}"
           subtraction: "{{a|int-b|int}}"
           multiplication: "{{a|int*b|int}}"
           division: "{{a|int/b|int if b|int !=0 else 'division is not possible'}}"
   tasks:
           - name: Displaying arithmetic result
             ansible.builtin.debug:
                     msg:
                             - "a value is {{a}} and b value is {{b}}"
                             - "Addition: {{addition}}"
                             - "Subtraction: {{subtraction}}"
                             - "Multiplication: {{multiplication}}"
                             - "Division: {{division}}"
