--- # Install Tomcat
- hosts: 192.168.2.114
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: Update the System Packages
            yum:
                    name: '*'
                    state: latest
          - name: Create a tomcat user
            user:
                    name: tomcat
          - name: Create a tomcat group
            group:
                    name: tomcat
          - name: Install Java
            ansible.builtin.yum:
                    name:
                            - java-1.8.0-openjdk
                    state: present
            when: ansible_facts.os_family == "RedHat"
          - name: Create a tomcat directory
            file:
                    path: /opt/KovairDevOps/tomcat8
                    owner: tomcat
                    group: tomcat
                    mode: 755
                    recurse: yes
          - name: Download & unarchive tomcat10
            unarchive:
                    src: https://downloads.apache.org/tomcat/tomcat-8/v8.5.95/bin/apache-tomcat-8.5.95.tar.gz
                    dest: /opt/KovairDevOps/tomcat8
                    remote_src: yes
                    extra_opts: [--strip-components=1]
          - name: Change ownership of tomcat directory
            file:
                    path: /opt/KovairDevOps/tomcat8
                    owner: tomcat
                    group: tomcat
                    mode: "u+rwx,g+rx,o=rx"
                    recurse: yes
                    state: directory
          - name: Copy Tomcat service from local to remote
            copy:
                    src: /etc/tomcat.service
                    dest: /etc/systemd/system/
                    mode: 0755
                    remote_src: yes
          - name: Start and Enable Tomcat 8 on sever
            systemd:
                    name: tomcat
                    state: started
                    daemon_reload: true
